[package]
name = "day-17"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { workspace = true }
rstest = { workspace = true }
divan = { workspace = true }

[[bench]]
name = "day-17-bench"
path = "benches/benchmarks.rs"
harness = false
